name: "Bug Report: Wrath"
description: Report a bug for Wrath
title: "Title here"
labels: ['🐛 Needs Investigation ❓', '🧬 Wrath ❄️']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Troubleshooting Steps
      description: |
        1. Type in game: `/edebug on`  (or `/ec`, on left **[Information]**, on top **[Debug]**)
        2. Test. Still have the issue?
           - **NO** Issue is probably another addon or plugin. Skip to the last step.
           - **YES** Type in game: `/estatus`  (or `/ec`, on top **[Status]**)
        3. Upload a **full, uncropped screenshot** showing the issue **and** the status panel.
        4. Finished with debugging? Repeat the first step.
      placeholder: Please go through the steps above and provide the requested information and a description of the issue.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe the expected behavior and what actually happened?
      description: Please try to be as descriptive as possible.
      placeholder: Try to explain what happened and what you expected the outcome to be.
    validations:
      required: false
  - type: textarea
    id: repoduce-steps
    attributes:
      label: Reproducing the issue.
      description: List steps in order to reproduce this issue.
      placeholder: Please make sure to use the debug command first. /edebug on
    validations:
      required: false
  - type: textarea
    id: errors
    attributes:
      label: Lua Errors
      description: If you have any Lua errors, please put them here.
      placeholder: "The first error is the most relevant error. (ex: 1 of 10)"
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Verification Steps
      description: This is important in order to rule out any other addons causing the issue.
      options:
        - label: I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
          required: true
        - label: I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
          required: true
        - label: I have not read any of these steps, please close my issue when you see it.
        - label: I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.
          required: true
